version: '3'

services:

  badges:
      container_name: badges
      restart: always
      working_dir: /app
      build:
          context: .
          dockerfile: Dockerfile
      volumes:
          - .:/app
      command: bash
